#
# Create and store an administrative password
#

- name: Check if an admin password already exists
  ansible.builtin.stat:
    path: '{{ admin_password_path }}'
  register: admin_password_stat

- name: Generate an admin password
  ansible.builtin.shell: |
    (tr -dc 'A-Za-z0-9!#$%&*+,-./:;=?@[\]^_{|}~' < /dev/urandom \
     | head -c 40 \
     && echo) > {{ admin_password_path }}
  when: not admin_password_stat.stat.exists

- name: Secure the admin password
  ansible.builtin.file:
    path: '{{ admin_password_path }}'
    owner: root
    group: root
    mode: '0400'
    state: file
