#
# Main Playbook for perfSONAR Testbed
#

- name: All Systems
  hosts: all
  tasks:
    - include_tasks: 'playbooks/{{ item }}.yml'
      with_items:
        - debug
        - fail2ban
        - all

- name: Testpoints
  hosts: testpoints
  tasks:
    - include_tasks: 'playbooks/{{ item }}.yml'
      with_items:
        - perfsonar

 
- name: Archive Servers
  hosts: archives
  tasks:
    - include_tasks: 'playbooks/{{ item }}.yml'
      with_items:
        - fail2ban
        - admin-password
        - perfsonar
        - archive


- name: Mesh Servers
  hosts: mesh_servers
  tasks:
    - include_tasks: 'playbooks/{{ item }}.yml'
      with_items:
        - fail2ban
        - mesh
